version: "3.8"

services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - BASE_URL=http://backend:8000 # URL interna para o backend
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000 # URL pública para o frontend acessar o backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
